server:
  httpPort: ":8080"

logger:
  env: "dev"
  logFilePath: "/logs/logs.log"

database:
  sslmode: "disable"

kafka:
  groupID: "order-service-group-id"
  topic: "order-service"
  brokers:
    - "kafka:9092"