env: "dev"

server:
  httpPort: ":8080"

database:
  sslmode: "disable"

kafka:
  groupID: "order-service-group-id"
  topic: "order-service"
  brokers:
    - "kafka:9092"

cache:
  defaultExpiration: "5m"
  cleanupInterval: "10m"
  preloadLimit: 100